name: Build and test

on: [push]

env:
  CC: gcc-11
  CXX: g++-11

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config Debug
    
    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C Debug